steps:
- name: gcr.io/cloud-builders/docker
  args: ['build', '-t', 'gcr.io/alpine-comfort-268715/cloudrun-demo:$BRANCH_NAME-$COMMIT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ["push", "gcr.io/alpine-comfort-268715/cloudrun-demo"]
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['beta', 'run', 'deploy', 'cloudrun-demo','--platform','managed','--allow-unauthenticated', '--image', 'gcr.io/alpine-comfort-268715/cloudrun-demo:$BRANCH_NAME-$COMMIT_SHA', '--region', 'us-central1']
